AWSTemplateFormatVersion: 2010-09-09
Parameters:
  VpcId:
    Type: 'AWS::EC2::VPC::Id'
    Description: >-
      Select a VPC that allows instances to access the Internet. Select same VPC
      in which LoadBalancer was created.
  SubnetId:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: >-
      Select at two subnets in your selected VPC. Select same Subnets in which
      LoadBalancer was created.
  ClusterName:
    Type: String
    Default: SampleCluster
    Description: Name for the cluster where we will be deploying code to the containers.
  EcsSecurityGroup:
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
    Description: Select security group in your selected VPC.
  AppTargetGroupName:
    Type: String
    Default: sample-target
    Description: Target Group Name
  Environment:
    Type: String
    Default: dev
    Description: Envirnoment -- 'prod' / 'uat' / 'dev' / 'qa'
  ECSTaskRoleArn:
    Type: String
    Default: 'arn:aws:iam::502193727466:role/ecsrole'
    Description: ECS Task role.
  ECSTaskExecutionRoleArn:
    Type: String
    Default: 'arn:aws:iam::502193727466:role/ecsrole'
    Description: ECS Task execution role
  DesiredCapacity:
    Type: Number
    Default: '0'
    Description: Number of instances to launch in your ECS cluster.
  MaxSize:
    Type: Number
    Default: '1'
    Description: Maximum number of instances that can be launched in your ECS cluster.
  ECSCluster:
    Type: String
    Default: SampleCluster
    Description: ECS CLuster App ARN
  ECSServiceName:
    Type: String
    Default: my-service
    Description: This will be used to create service for ECS cluster.
  ContainerPort:
    Type: Number
    Default: 80
    Description: 'For Container Port'
  HealthCheckPath:
    Type: String
    Default: /
    Description: For Container Health Check
  HttpForwardRuleForNginx:
    Type: String
    Default: sample
  ALBListenerHttps:
    Type: String
    Default: >-
      arn:aws:elasticloadbalancing:us-east-1:502193727466:listener/app/Test-LB/fd8ebccc546d7f49/6a979d3636ef2dc4
    Description: 'Https/Http ListenerArn, where we want to add the TargetGroup'
  ECRRepositoryName:
    Type: String
    Default: sample-repo
    Description: ECR repo name
  EcrRepoArn:
    Type: String
    Default: 502193727466.dkr.ecr.us-east-1.amazonaws.com
    Description: ECR repo ARN. <Do not add repo name>
  ListenerRulePriority:
    Type: Number
    Default: 1
    Description: Listener Rule priority.
Resources:
  MYECSCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: !Ref ECSCluster
  AppCloudwatchLogsGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Join 
        - /
        - - !Ref ClusterName
          - !Ref ECSServiceName
      RetentionInDays: 14
  EcrRepo:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName: !Ref ECRRepositoryName
      Tags:
        - Key: stack-id
          Value: !Ref 'AWS::StackName'
  taskdef:
    Type: 'AWS::ECS::TaskDefinition'
    DependsOn:
      - AppTargetGroup
      - ECSALBListenerRuleForTG
    Properties:
      RequiresCompatibilities:
        - FARGATE
      Family: !Ref ECSServiceName
      ContainerDefinitions:
        - Name: !Ref ECSServiceName
          Image: !Join 
            - ':'
            - - !Join 
                - /
                - - !Ref EcrRepoArn
                  - !Ref ECRRepositoryName
              - latest
          Essential: 'true'
          PortMappings:
            - HostPort: !Ref ContainerPort
              Protocol: tcp
              ContainerPort: !Ref ContainerPort
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Join 
                - /
                - - !Ref ClusterName
                  - !Ref ECSServiceName
              awslogs-region: ap-south-1
              awslogs-stream-prefix: !Ref ECSServiceName
          Environment:
            - Name: NODE_ENV
              Value: !Ref Environment
            - Name: PORT
              Value: !Ref ContainerPort
      NetworkMode: awsvpc
      Memory: '1024'
      Cpu: '512'
      TaskRoleArn: !Ref ECSTaskRoleArn
      ExecutionRoleArn: !Ref ECSTaskExecutionRoleArn
  service:
    Type: 'AWS::ECS::Service'
    DependsOn: taskdef
    Properties:
      ServiceName: !Ref ECSServiceName
      Cluster: !Ref ECSCluster
      LaunchType: FARGATE
      DesiredCount: !Ref DesiredCapacity
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      HealthCheckGracePeriodSeconds: 5

      LoadBalancers:
        - ContainerName: !Ref ECSServiceName
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref AppTargetGroup
      TaskDefinition: !Ref taskdef
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups: !Ref EcsSecurityGroup
          Subnets: !Ref SubnetId
          AssignPublicIp: ENABLED
      Tags:
        - Key: Project
          Value: training
        - Key: resource
          Value: ecs
        - Key: env
          Value: dev
        - Key: 'created-by'
          Value: Dhruv Singh
      PropagateTags: SERVICE
  AppTargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: !Ref HealthCheckPath
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Name: !Ref AppTargetGroupName
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 2
      VpcId: !Ref VpcId
      TargetType: ip
  ECSALBListenerRuleForTG:
    Type: 'AWS::ElasticLoadBalancingV2::ListenerRule'
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref AppTargetGroup
      Conditions:
        - Field: http-header
          HttpHeaderConfig:
            HttpHeaderName: X-App-Name
            Values:
              - !Ref HttpForwardRuleForNginx
      ListenerArn: !Ref ALBListenerHttps
      Priority: !Ref ListenerRulePriority
Outputs:
  service:
    Value: !Ref service
  taskdef:
    Value: !Ref taskdef
  AppTargetGroup:
    Value: !Ref AppTargetGroup
  ECRRepo:
    Value: !Join 
      - ':'
      - - !Join 
          - /
          - - !Ref EcrRepoArn
            - !Ref ECRRepositoryName
        - latest